sudo: false

language: php

matrix:
  include:
    - php: hhvm-stable
      sudo: required
      dist: trusty
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: hhvm-stable
  fast_finish: true

script:
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

before_script:
  - echo hhvm.php7.all=1 >> /etc/hhvm/php.ini
  - composer self-update
  - composer install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
